### ISSUE TITLE
help for to configure plugins

### ISSUE THREAD

**Issue by OrionRandD** [SethosII/reveal.js-jump-plugin#3]
Hi, could you help me to install plugins in my
$HOME/reveal-slides/reveal.js/js/reveal.js  file?
I have downloaded some of them, including yours and
put it in the above file, but they do not work and I do not get org-mode exported
when i add this bit inside that file.
I really do not know the exact place to put these initialization configurations

------------------------------------
// Script dependencies to load
            dependencies: [
            // Jump plugin
			{ src: 'plugin/jump/jump/jump.js', async: true }

            // other dependencies
                { src: 'plugin/quiz/quis/js/quiz.js', async: true, callback: function() { prepareQuizzes({}); } }

            // other dependencies
                { src: 'plugin/toc-progress/plugin/toc-progress.js', async: true, callback: function() { toc_progress.initialize(); toc_progress.create(); } }
            ]
		},

		// Flags if Reveal.initialize() has been called
		initialized = false,

Reveal.initialize({
    ...
    coursemod: {
        enabled: true
    },
    ...
    dependencies: [
        ...
        { src: 'plugin/coursemod/coursemod/coursemod.js', async: true}
        { src: 'plugin/menu/menu.js' }
    ]
});

**Comment by lechten** [comment]
As you mention org-mode, allow me to point you to other places: There is [org-reveal](https://github.com/yjwen/org-reveal) to create reveal.js presentations from Org mode files, my fork [org-re-reveal](https://gitlab.com/oer/org-re-reveal), which in turn is the core of [oer-reveal](https://gitlab.com/oer/oer-reveal) and [emacs-reveal](https://gitlab.com/oer/emacs-reveal). The latter two embed several reveal.js plugins, including coursemod, jump, quiz, and toc-progress, which you mention in your code.

Anyways, the initialization code should not be embedded in reveal.js but in your HTML file.
