### ISSUE TITLE
Jump to the top of a vertical stack

### ISSUE THREAD

**Issue by ericwongmusic** [SethosII/reveal.js-jump-plugin#6]
Is it possible to have a shortcut (e.g. Shift up arrow) to jump to the top of a vertical stack?

**Comment by SethosII** [comment]
@ericwongmusic Currently this isn't possible but it should be possible to include this. I will have a look.

**Comment by SethosII** [comment]
@ericwongmusic I added a commit (https://github.com/SethosII/reveal.js-jump-plugin/commit/72f036920f451fb334b72e10cc2ee2e91d98511b) which adds this functionality. The keybindings are `shift`+`page up` and `page down`. See if it works for you.
